#!/bin/sh

##
## \brief  Get the date from a NTP server and maintain the RTC.
##
## \author Christophe Blaess <cpb@logilin.fr>.
##
## \copyright 2018-2022 Logilin.
##

## \brief  The delay (in seconds) to retry joining the NTP server after a failure.
RETRY_AFTER_FAILURE_DELAY=30

## \brief  The delay (in seconds) to retry joining the NTP server after a successfull clock update.
RETRY_AFTER_SUCCESS_DELAY=600

## \brief  The NTP server address.
NTP_SERVER=pool.ntp.org

## \brief The `ntpd` tool options. The default is Busybox-based `ntpd`.
NTPD_OPTIONS="-n -q -p"



# First, try to restore the date from the realtime clock.
hwclock -s


# Read the year from the system clock.
year=$(date +%Y)

# If the year is invalid,
if [ ${year} -lt 2022]; then

	# set a default date of 2022/01/01 12:00:00,
	# it will seem less weird than 1970/01/01.
	date 010112002022
fi

while true
do
	wait_delay=${RETRY_AFTER_FAILURE_DELAY}

	# Check if the server is reachable.
	if ping -c1 -W1 "${NTP_SERVER}" >/dev/null 2>&1
	then
		# If we succeed in setting the date,
		if ntpd ${NTPD_OPTIONS} "${NTP_SERVER}"
		then
			# store it in the hardware clock.
			hwclock -w
			wait_delay=${RETRY_AFTER_SUCCESS_DELAY}
		fi
	fi

	sleep ${wait_delay}
done
